---
  - name: Installing Metricbeat
    hosts: webservers
    become: yes
    tasks:

    - name: Download Metricbeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install Metricbeat deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Put in Metricbeat playbook
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure system module
      command: metricbeat modules enable docker

    - name: Setup Metricbeat
      command: metricbeat setup

    - name: Start Metricbeat Service
      command: service metricbeat start
